SELECT TOP (1000) [Transaction_ID]
      ,[Item]
      ,[Quantity]
      ,[Price_Per_Unit]
      ,[Total_Spent]
      ,[Payment_Method]
      ,[Location]
      ,[Transaction_Date]
  FROM [Sales].[dbo].[clean_cafe_sales]